package com.avalon.client;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

import com.avalon.client.entry.RoomEntry;
import com.avalon.client.entry.UserEntry;
import com.avalon.packet.CPacket;
import com.avalon.util.GameMode;
import com.avalon.util.ImageUtil;
import com.fasterxml.jackson.core.JsonGenerationException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.glass.events.WindowEvent;

/**
 *
 * @author CAUCSE
 * Created by 강수현
 * Modified by 장익환
 */
public class LobbyFrame extends javax.swing.JFrame implements ActionListener{
	
	// 게임 모드
	static GameMode  MODE = new GameMode();
	
	ImageUtil iUtil = new ImageUtil();
		
    private UIThread thread;
	private ClientMgr cMgr;
	
	ObjectMapper om = new ObjectMapper();
	/**
     * Creates new form LobbyFrame
     */
	public LobbyFrame(ClientMgr tMgr,UIThread thr) {
		this.thread = thr;
		cMgr = tMgr;
		
		
		initComponents();
		this.setVisible(false);
		
	}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        waitingRoom1 = new javax.swing.JScrollPane();
        rooms1 = new javax.swing.JTable();
        waitingRoom2 = new javax.swing.JScrollPane();
        rooms2 = new javax.swing.JTable();
        waitingRoom3 = new javax.swing.JScrollPane();
        rooms3 = new javax.swing.JTable();
        waitingRoom4 = new javax.swing.JScrollPane();
        rooms4 = new javax.swing.JTable();
        jLabelBackground3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        myPicture = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        myScore = new javax.swing.JLabel();
        myScore1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelBackground2 = new javax.swing.JLabel();
        jLabelBackground1 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(new java.awt.FlowLayout());
        
        setTitle("아발론 온라인 - 대기실");
		setResizable(false);
		
		this.addWindowListener(new WindowListener() {
			public void windowActivated(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			
			public void windowClosed(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
			}

			
			public void windowClosing(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				if(JOptionPane .showConfirmDialog(null, "게임을 종료하시겠습니까?","확인",JOptionPane.YES_NO_OPTION) == 0){
		    		System.exit(0);
		    	}
				return;
			}

			
			public void windowDeactivated(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			
			public void windowDeiconified(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			
			public void windowIconified(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			
			public void windowOpened(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				
			}
		});
		
		Dimension monitorSize = Toolkit.getDefaultToolkit().getScreenSize();
		Dimension frameSize =  getSize();
		if(frameSize.height > monitorSize.height){frameSize.height = monitorSize.height;}
		if(frameSize.width > monitorSize.width) {frameSize.width = monitorSize.width;}
		setLocation((monitorSize.width - frameSize.width)/2, (monitorSize.height - frameSize.height)/2);


		jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnExit.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnCreateRoom.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnHelp.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnEnterRoom.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        
        columnName2 = new String[]{"방번호", "방제", "방장", "상태"};
        rooms = new Object[0][4];
        
        model2 = new DefaultTableModel(rooms,columnName2);
        
        rooms1.setModel(model2);
        
        waitingRoom1.setViewportView(rooms1);
        rooms1.getColumnModel().getColumn(0).setResizable(false);
        rooms1.getColumnModel().getColumn(0).setPreferredWidth(30);
        rooms1.getColumnModel().getColumn(1).setResizable(false);
        rooms1.getColumnModel().getColumn(2).setResizable(false);
        rooms1.getColumnModel().getColumn(2).setPreferredWidth(100);
        rooms1.getColumnModel().getColumn(3).setResizable(false);
        rooms1.getColumnModel().getColumn(3).setPreferredWidth(30);
        
         rooms1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         rooms1.addMouseListener(new MouseListener(){

			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				int row = rooms1.getSelectedRow();
				int column = rooms1.getSelectedColumn();
				
				CPacket tpkt = new CPacket();
	            tpkt.setToken(thread.getACCESS_TOKEN());
	            
	            tpkt.setTask_type("SEND");
	            tpkt.setTask_title("ENTERROOM");
	            HashMap<String,String> msg = new HashMap<String,String>();
	            msg.put("USER", thread.me.getJSON2());
	            msg.put("ROOM", thread.Rooms.get(row).getJSON());
	            try {
					tpkt.setMessage(om.writeValueAsString(msg));
					cMgr.SendMessage(tpkt);
				} catch (JsonGenerationException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (JsonMappingException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
	            
			}

			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
        	 
         });

        jTabbedPane1.addTab("채널 1", waitingRoom1);
        
       
        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 520, 230));

        jLabelBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/channel_list.png"))); // NOI18N
        jPanel3.add(jLabelBackground3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 600, 300));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setMaximumSize(new java.awt.Dimension(0, 0));
        
        
        columnName = new String[]{"이름","상태","전적"};
        friends = new Object[0][3];
        
        model = new DefaultTableModel(friends,columnName);
        
        jTable5.setModel(model);
        
        jScrollPane5.setViewportView(jTable5);
        
        jTable5.getColumnModel().getColumn(0).setResizable(false);
        jTable5.getColumnModel().getColumn(0).setPreferredWidth(300);
        jTable5.getColumnModel().getColumn(1).setResizable(false);
        jTable5.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable5.getColumnModel().getColumn(2).setResizable(false);
        jTable5.getColumnModel().getColumn(2).setPreferredWidth(100);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 245, 130));

        myPicture.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(myPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 70, 80));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("전적 : ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("최근접속 : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        myScore.setForeground(new java.awt.Color(255, 255, 255));
        myScore.setText(" ");
        jPanel2.add(myScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 68, -1));

        myScore1.setForeground(new java.awt.Color(255, 255, 255));
        myScore1.setText(" ");
        myScore1.setToolTipText("");
        jPanel2.add(myScore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 68, -1));
        myScore1.getAccessibleContext().setAccessibleName("");

        jLabel4.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("사용자 List");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 125, -1, -1));

        jLabelBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/myinfo.png"))); // NOI18N
        jPanel2.add(jLabelBackground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, 300));

        jLabelBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lobby/logo.png"))); // NOI18N
        jPanel1.add(jLabelBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 250, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lobby/background.png"))); // NOI18N
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    	if(JOptionPane.showConfirmDialog(this, "게임을 종료하시겠습니까?","확인",JOptionPane.YES_NO_OPTION) == 0){
    	//  서버에 방 삭제 통지

            CPacket tpkt = new CPacket();
            tpkt.setToken(thread.getACCESS_TOKEN());
            
            tpkt.setTask_type("SEND");
            tpkt.setTask_title("DELUSER");
            tpkt.setMessage(thread.me.getJSON2());
            cMgr.SendMessage(tpkt);
            
    		
    	}
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
       	thread.setGamemode(MODE.RULE);
    	thread.setCwindow(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    	thread.setGamemode(MODE.ROOM);
    	thread.setCwindow(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    	thread.setGamemode(MODE.MAKE_ROOM);
    	thread.setCwindow(true);
    }//GEN-LAST:event_jLabel6MouseClicked
    /**
     * @param args the command line arguments
     */
    
    public void setUser(UserEntry user){
    	System.out.println("http://graph.facebook.com/"+user.fbuser.getId()+"/picture?type=large");
    	String profile_url = "http://graph.facebook.com/"+user.fbuser.getId()+"/picture?type=large";
    	Image image = iUtil.getImage(profile_url,70,80);
    	
    	
    	this.myPicture.setIcon(new ImageIcon(image));
    	jLabel2.setText(user.fbuser.getName()+"님 환영합니다.");
    	jLabel3.setText("나의전적 : "+user.getScore());
    	this.repaint();
    }
     public void addUser(ArrayList<UserEntry> friends) {
    	 int k = 0;
    	 this.friends = new Object[friends.size()][3];
    	 
    	for(UserEntry friend : friends ) {
    		this.friends[k][0] = friend.getName();
    		this.friends[k][1] = friend.getState();
    		this.friends[k][2] = friend.getScore();
    		k++;
    	}
    	model = new DefaultTableModel(this.friends,columnName);
    	 jTable5.setModel(model);
    	 jTable5.getColumnModel().getColumn(0).setResizable(false);
         jTable5.getColumnModel().getColumn(0).setPreferredWidth(300);
         jTable5.getColumnModel().getColumn(1).setResizable(false);
         jTable5.getColumnModel().getColumn(1).setPreferredWidth(100);
         jTable5.getColumnModel().getColumn(2).setResizable(false);
         jTable5.getColumnModel().getColumn(2).setPreferredWidth(100);
    	 //autoColSize(jTable5,model);
    	 this.repaint();
    	 
    	 
     }
     
     public void addRoom(ArrayList<RoomEntry> rooms) {
    	 int k = 0;
    	 this.rooms = new Object[rooms.size()][4];
    	 
    	 //columnName2 = new String[]{"방번호", "방제", "방장", "상태"};
    	for(RoomEntry room : rooms ) {
    		this.rooms[k][0] = ""+room.getNum();
    		this.rooms[k][1] = room.getTitle();
    		this.rooms[k][2] = room.me.getName();
    		if(!room.isState())
    			this.rooms[k][3] = "대기중";
    		else
    			this.rooms[k][3] = "게임중";
    		k++;
    	}
    	model2 = new DefaultTableModel(this.rooms,columnName2);
    	 rooms1.setModel(model2);
    	 rooms1.getColumnModel().getColumn(0).setResizable(false);
         rooms1.getColumnModel().getColumn(0).setPreferredWidth(30);
         rooms1.getColumnModel().getColumn(1).setResizable(false);
         rooms1.getColumnModel().getColumn(2).setResizable(false);
         rooms1.getColumnModel().getColumn(2).setPreferredWidth(100);
         rooms1.getColumnModel().getColumn(3).setResizable(false);
         rooms1.getColumnModel().getColumn(3).setPreferredWidth(30);
    	 //autoColSize(jTable5,model);
    	 this.repaint();
    	 
    	 
     }
     
     private void autoColSize(JTable table, TableModel model)
     {
      TableColumn column = null;
      Component comp = null;
      int headerWidth = 0;
      int cellWidth = 0;
      int font = 11;
      for (int i = 0, n = model.getColumnCount(); i < n; i++)
      {
       column = table.getColumnModel().getColumn(i);
       try
       {
        headerWidth = column.getHeaderValue().toString().length()
          * font;
        column.setPreferredWidth(headerWidth);
       }
       catch (Exception e)
       {
       }
      }
     }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBackground1;
    private javax.swing.JLabel jLabelBackground2;
    private javax.swing.JLabel jLabelBackground3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel myPicture;
    private javax.swing.JLabel myScore;
    private javax.swing.JLabel myScore1;
    private javax.swing.JTable rooms1;
    private javax.swing.JTable rooms2;
    private javax.swing.JTable rooms3;
    private javax.swing.JTable rooms4;
    private javax.swing.JScrollPane waitingRoom1;
    private javax.swing.JScrollPane waitingRoom2;
    private javax.swing.JScrollPane waitingRoom3;
    private javax.swing.JScrollPane waitingRoom4;
    private DefaultTableModel model;
    private DefaultTableModel model2;
    private String[] columnName;
    private Object[][] friends;
    
    private String[] columnName2;
    private Object[][] rooms;
    // End of variables declaration//GEN-END:variables
	
	public void actionPerformed(ActionEvent arg0) {
		// TODO Auto-generated method stub
		
	}
}
