/**
 *
 * @author CAUCSE
 * Created by 강수현
 * Modified by 장익환
 */
package com.avalon.client;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.WindowListener;
import java.io.IOException;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import com.avalon.client.entry.MessageEntry;
import com.avalon.client.entry.RoomEntry;
import com.avalon.client.entry.StoneEntry;
import com.avalon.client.entry.UserEntry;
import com.avalon.packet.CPacket;
import com.avalon.util.GameMode;
import com.avalon.util.ImageUtil;
import com.fasterxml.jackson.core.JsonGenerationException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
public class RoomFrame extends javax.swing.JFrame {

    private UIThread thread;
	private ClientMgr cMgr;
	private RoomEntry roomInfo;
	ImageUtil iUtil = new ImageUtil();
	/**
     * Creates new form LobbyFrame
     */
	
	// 게임 모드
		static GameMode  MODE = new GameMode();
    public RoomFrame(ClientMgr tMgr,UIThread thr) {
		this.thread = thr;
		cMgr = tMgr;
		roomInfo = new RoomEntry();
		
		
		initComponents();
		
		//원 그리기
		CirclePanel p = new CirclePanel();

		add(p, BorderLayout.CENTER);
		this.repaint();
		this.setVisible(false);
	}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new CirclePanel();
        
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelBackground3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        myPicture1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        myPicture = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        myScore = new javax.swing.JLabel();
        myScore1 = new javax.swing.JLabel();
        jLabelBackground4 = new javax.swing.JLabel();
        jLabelBackground1 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(new java.awt.FlowLayout());
        
        setTitle("아발론 온라인 - " );
		setResizable(false);
		
		this.addWindowListener(new WindowListener() {
			
			public void windowActivated(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			
			public void windowClosed(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
			}

			
			public void windowClosing(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				if(JOptionPane .showConfirmDialog(null, "게임을 종료하시겠습니까?","확인",JOptionPane.YES_NO_OPTION) == 0){
		    		System.exit(0);
		    	}
				return;
			}

			
			public void windowDeactivated(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			
			public void windowDeiconified(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			
			public void windowIconified(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			
			public void windowOpened(java.awt.event.WindowEvent e) {
				// TODO Auto-generated method stub
				
			}
		});
		
		Dimension monitorSize = Toolkit.getDefaultToolkit().getScreenSize();
		Dimension frameSize =  getSize();
		if(frameSize.height > monitorSize.height){frameSize.height = monitorSize.height;}
		if(frameSize.width > monitorSize.width) {frameSize.width = monitorSize.width;}
		setLocation((monitorSize.width - frameSize.width)/2, (monitorSize.height - frameSize.height)/2);


        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked (java.awt.event.MouseEvent evt) {
        		jPanel4MouseClicked(evt);
        	}
        });
        

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 600, 410));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("입력");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 460, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(3);
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 520, -1));

        jLabelBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/chatting.png"))); // NOI18N
        jPanel3.add(jLabelBackground3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 600, 150));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("이름");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lithos Pro Regular", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("0:00");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("남은시간 : ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("이름");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("전적 : 3승8패");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        myPicture1.setForeground(new java.awt.Color(255, 255, 255));
        myPicture1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(myPicture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 79, 87));

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enemy");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("You");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnPass.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnTurnOff.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnQuit.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        myPicture.setForeground(new java.awt.Color(255, 255, 255));
        myPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(myPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 79, 87));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("전적 : 4승 2패");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        myScore.setForeground(new java.awt.Color(255, 255, 255));
        myScore.setText(" ");
        jPanel2.add(myScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 68, -1));

        myScore1.setForeground(new java.awt.Color(255, 255, 255));
        myScore1.setText(" ");
        myScore1.setToolTipText("");
        jPanel2.add(myScore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 68, -1));
        myScore1.getAccessibleContext().setAccessibleName("");

        jLabelBackground4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/dashboard.png"))); // NOI18N
        jPanel2.add(jLabelBackground4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 250, 510));

        jLabelBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/game/logo.png"))); // NOI18N
        jPanel1.add(jLabelBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 150, 60));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lobby/background.png"))); // NOI18N
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void jButton1MouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	//public CPacket(String token, String task_type,String task_title,String message) {
    	// 1. Create MessageEntry
    	 MessageEntry tMsg = new MessageEntry();
    	 tMsg.setFrom_id(thread.me.getId());
    	if(thread.enemy.getId().equals("")){
    		tMsg.setTo_id(thread.me.getId());
    	}
    	tMsg.setMessage(jTextField1.getText());
    	CPacket tpkt = new CPacket();
        tpkt.setToken(thread.getACCESS_TOKEN());
        
        tpkt.setTask_type("SEND");
        tpkt.setTask_title("CHAT");
        try {
			tpkt.setMessage(tMsg.getJSON());
			cMgr.SendMessage(tpkt);
		} catch (JsonGenerationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (JsonMappingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
		
	}
    
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {
    	//JOptionPane.showMessageDialog(null, " "+evt.getX()+" "+evt.getY());
    	int x = evt.getX();
    	int y = evt.getY();
    	
    	for(int i = 0 ; i < jPanel4.stones.length ; i++) {
    		StoneEntry temp = jPanel4.stones[i];
    		if(x >= temp.getX() && temp.getX() + temp.getWidth()  >= x && y >= temp.getY() && temp.getY() + temp.getHeight() >= y) {
    			//JOptionPane.showMessageDialog(null, i+" 번돌 클릭됨");
    			jPanel4.changeColor(i);
    			break;
    		}
    	}
    }
    
	private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    	if(JOptionPane.showConfirmDialog(this, "대기실로 돌아가겠습니까?","확인",JOptionPane.YES_NO_OPTION) == 0){
    		
    	//  서버에 방 삭제 통지

            CPacket tpkt = new CPacket();
            tpkt.setToken(thread.getACCESS_TOKEN());
            
            tpkt.setTask_type("SEND");
            tpkt.setTask_title("DELROOM");
            tpkt.setMessage(roomInfo.getJSON());
            cMgr.SendMessage(tpkt);
            
    		
    	}
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    	if(JOptionPane.showConfirmDialog(this, "정말로 기권하겠습니까?","확인",JOptionPane.YES_NO_OPTION) == 0){

    	}
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void setRoomInfo(RoomEntry room) {
    	this.roomInfo = room;
    	this.setTitle("아발론 온라인 - "+room.getTitle() );
    	roomInfo.me = thread.me;
    	setMe();
    	if(this.roomInfo.getOwner().equals(thread.me.getId())){
    		setEnemy(roomInfo.getEnemy());
    	}
    }
    
    public void setMe(){

    	String profile_url = "http://graph.facebook.com/"+roomInfo.me.getId()+"/picture?type=large";
    	Image image = iUtil.getImage(profile_url,70,80);
    	
    	
    	// My Setting
    	this.myPicture.setIcon(new ImageIcon(image));
    	jLabel12.setText(roomInfo.me.getName());
    	jLabel3.setText("전적 : "+roomInfo.me.getScore());
    	
    	this.repaint();
    }
    
    public void setEnemy(UserEntry enemy) {
    	this.roomInfo.enemy = enemy;
    	thread.enemy = enemy;

    	String profile_url2 = "http://graph.facebook.com/"+roomInfo.enemy.getId()+"/picture?type=large";
    	Image image2 = iUtil.getImage(profile_url2,70,80);
    	
    	// Enemy Setting
    	this.myPicture1.setIcon(new ImageIcon(image2));
    	jLabel4.setText(roomInfo.enemy.getName());
    	jLabel10.setText("전적 : "+roomInfo.enemy.getScore());
    	
    	
    	this.repaint();
    }
    
    public void setMessage(MessageEntry tmsg) {
    	String from_name="";
    	String to_name="";
    	for(UserEntry user : thread.Friends){
    		if(user.getId().equals(tmsg.getFrom_id())){
    			from_name = user.getName();
    		}
    		if(user.getId().equals(tmsg.getTo_id())){
    			to_name = user.getName();
    		}
    	}
    	this.jTextArea1.setText(jTextArea1.getText()+"\n["+from_name+"] "+tmsg.getMessage());
    }
    
    public void clearRoom() {
    	this.roomInfo = new RoomEntry();
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBackground1;
    private javax.swing.JLabel jLabelBackground3;
    private javax.swing.JLabel jLabelBackground4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private CirclePanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel myPicture;
    private javax.swing.JLabel myPicture1;
    
    private javax.swing.JLabel myScore;
    private javax.swing.JLabel myScore1;
    // End of variables declaration//GEN-END:variables
}
